-- ==========================================
-- SCRIPT DE BASE DE DATOS: TERREMOTO VENEZUELA
-- Ejecuta este script en el editor SQL de Supabase (SQL Editor -> New Query)
-- ==========================================

-- 1. Crear la tabla de personas
CREATE TABLE IF NOT EXISTS public.personas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre text NOT NULL,
    cedula text NOT NULL UNIQUE,
    edad integer,
    ultima_ubicacion text,
    telefono_contacto text,
    observaciones text,
    estado text NOT NULL DEFAULT 'Desaparecido' CHECK (estado IN ('Desaparecido', 'Encontrado')),
    ubicacion_encontrado text,
    encontrado_por text,
    encontrado_por_cedula text,
    es_menor boolean DEFAULT false NOT NULL,
    foto_url text,
    fecha_registro timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    fecha_actualizacion timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Para asegurar compatibilidad si la tabla ya existe
ALTER TABLE public.personas ADD COLUMN IF NOT EXISTS encontrado_por text;
ALTER TABLE public.personas ADD COLUMN IF NOT EXISTS encontrado_por_cedula text;
ALTER TABLE public.personas ADD COLUMN IF NOT EXISTS es_menor boolean DEFAULT false NOT NULL;

-- 2. Habilitar Seguridad a Nivel de Fila (RLS)
ALTER TABLE public.personas ENABLE ROW LEVEL SECURITY;

-- 3. Crear PolÃ­ticas de Acceso para la Tabla 'personas'
-- Permite que cualquiera pueda buscar y ver personas
CREATE POLICY "Permitir lectura pÃºblica de personas" 
ON public.personas FOR SELECT 
USING (true);

-- Permite que cualquier persona reporte (inserte) un desaparecido
CREATE POLICY "Permitir registro pÃºblico de desaparecidos" 
ON public.personas FOR INSERT 
WITH CHECK (true);

-- Solo usuarios autenticados (el administrador) pueden actualizar estados
CREATE POLICY "Permitir actualizaciÃ³n solo a administradores" 
ON public.personas FOR UPDATE 
TO authenticated 
USING (true);

-- Solo usuarios autenticados (el administrador) pueden eliminar registros
CREATE POLICY "Permitir eliminaciÃ³n solo a administradores" 
ON public.personas FOR DELETE 
TO authenticated 
USING (true);


-- 4. Crear el Bucket de Almacenamiento para Fotos
-- Inserta la configuraciÃ³n del bucket en el esquema de almacenamiento de Supabase
INSERT INTO storage.buckets (id, name, public) 
VALUES ('fotos-personas', 'fotos-personas', true)
ON CONFLICT (id) DO NOTHING;

-- 5. PolÃ­ticas de Acceso para las Fotos (Storage)
-- Permite que cualquiera pueda ver las fotos subidas
CREATE POLICY "Permitir lectura pÃºblica de fotos"
ON storage.objects FOR SELECT
USING (bucket_id = 'fotos-personas');

-- Permite que cualquiera pueda subir una foto de perfil de un desaparecido
CREATE POLICY "Permitir subida pÃºblica de fotos"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'fotos-personas');

-- Solo administradores autenticados pueden borrar fotos
CREATE POLICY "Permitir borrado de fotos solo a administradores"
ON storage.objects FOR DELETE
TO authenticated
USING (bucket_id = 'fotos-personas');


-- 6. Indices de rendimiento para busqueda y filtros
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- Default sort (estado ASC, fecha_registro DESC) y queries COUNT de stats
CREATE INDEX IF NOT EXISTS idx_personas_estado_fecha
  ON public.personas (estado, fecha_registro DESC);

-- Filtros de rango de edad y ORDER BY edad
CREATE INDEX IF NOT EXISTS idx_personas_edad
  ON public.personas (edad)
  WHERE edad IS NOT NULL;

-- Busqueda por prefijo de nombre (ILIKE 'query%') y ORDER BY nombre
CREATE INDEX IF NOT EXISTS idx_personas_nombre_btree
  ON public.personas (nombre);

-- Busqueda por contenido en nombre (ILIKE '%query%')
CREATE INDEX IF NOT EXISTS idx_personas_nombre_trgm
  ON public.personas USING GIN (nombre gin_trgm_ops);

-- Busqueda por contenido en cedula (ILIKE '%query%')
CREATE INDEX IF NOT EXISTS idx_personas_cedula_trgm
  ON public.personas USING GIN (cedula gin_trgm_ops);

-- Filtros de ubicacion (tipoUbicacion y texto libre)
CREATE INDEX IF NOT EXISTS idx_personas_ultima_ubicacion_trgm
  ON public.personas USING GIN (ultima_ubicacion gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_personas_ubicacion_encontrado_trgm
  ON public.personas USING GIN (ubicacion_encontrado gin_trgm_ops);


-- 7. Insertar Datos de Demostracion ficticios (Opcional, borrar si no se desea)
INSERT INTO public.personas (nombre, cedula, edad, ultima_ubicacion, telefono_contacto, observaciones, estado, ubicacion_encontrado)
VALUES 
('Persona Demo 001', 'V-00000001', 34, 'Ubicacion demo', '0000-0000000', 'Registro ficticio para pruebas locales.', 'Desaparecido', NULL),
('Persona Demo 002', 'V-00000002', 28, 'Ubicacion demo', '0000-0000000', 'Registro ficticio para pruebas locales.', 'Desaparecido', NULL),
('Persona Demo 003', 'V-00000003', 62, 'Ubicacion demo', '0000-0000000', 'Registro ficticio para pruebas locales.', 'Encontrado', 'Ubicacion demo'),
('Persona Demo 004', 'V-00000004', 45, 'Ubicacion demo', '0000-0000000', 'Registro ficticio para pruebas locales.', 'Desaparecido', NULL)
ON CONFLICT (cedula) DO NOTHING;
